#!/usr/bin/env bash
#
# Vendor Render's OSS skills into ./skills.
#
# renderinc/skills is the source of truth and is mirrored publicly to
# render-oss/skills. Production syncs use that public mirror; --repo makes the
# same transformation testable against a local source clone.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="https://github.com/render-oss/skills"
REF="main"
DEST="$ROOT/skills"

usage() {
  cat <<'EOF'
Usage: scripts/sync-skills.sh [options]

Options:
  --repo <url-or-path>  Source repository (default: https://github.com/render-oss/skills)
  --ref <git-ref>       Branch, tag, or commit to sync (default: main)
  --dest <path>         Destination directory (default: ./skills)
  -h, --help            Show this help
EOF
}

require_value() {
  if [[ $# -lt 2 || -z "$2" ]]; then
    echo "Missing value for $1" >&2
    usage >&2
    exit 2
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      require_value "$@"
      REPO="$2"
      shift 2
      ;;
    --ref)
      require_value "$@"
      REF="$2"
      shift 2
      ;;
    --dest)
      require_value "$@"
      DEST="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$DEST" || "$DEST" == "/" ]]; then
  echo "Refusing unsafe destination: ${DEST:-<empty>}" >&2
  exit 2
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Cloning ${REPO} @ ${REF} ..."
git clone --quiet "$REPO" "$TMP/repo"
if ! git -C "$TMP/repo" checkout --quiet "$REF"; then
  git -C "$TMP/repo" fetch --quiet origin "$REF"
  git -C "$TMP/repo" checkout --quiet FETCH_HEAD
fi

COMMIT="$(git -C "$TMP/repo" rev-parse HEAD)"
SOURCE_DIR="$TMP/repo/skills"
STAGED="$TMP/output"

if [[ ! -d "$SOURCE_DIR" ]]; then
  echo "Skills directory not found in ${REPO} @ ${REF}" >&2
  exit 1
fi

mkdir -p "$STAGED"
count=0

# Copy every Render skill and all of its distributable references/assets.
for skill_dir in "$SOURCE_DIR"/render-*; do
  [[ -d "$skill_dir" ]] || continue
  if [[ ! -f "$skill_dir/SKILL.md" ]]; then
    echo "Render skill is missing SKILL.md: ${skill_dir}" >&2
    exit 1
  fi
  cp -R "$skill_dir" "$STAGED/$(basename "$skill_dir")"
  count=$((count + 1))
done

if [[ "$count" -eq 0 ]]; then
  echo "No render-* skills found in ${REPO} @ ${REF}" >&2
  exit 1
fi

# Match the public Copybara destination: eval inputs and internal eval docs are
# source-only and must not enter downstream plugin packages.
find "$STAGED" -type f \
  \( -name "evals.json" -o -name "skillet.eval.yaml" -o -name "EVALS.md" \) \
  -delete

# Record provenance so we (and tests) can see exactly what is vendored.
cat > "$STAGED/.sync-source" <<EOF
source: ${REPO}
ref: ${REF}
commit: ${COMMIT}
note: generated by scripts/sync-skills.sh; do not edit vendored skills by hand.
EOF

echo "Refreshing ${DEST} ..."
mkdir -p "$(dirname "$DEST")"
rm -rf "$DEST"
mv "$STAGED" "$DEST"

echo "Vendored ${count} skills from ${COMMIT} into ${DEST}."
